# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTATopicOption',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('option_name', models.CharField(max_length=2400)),
                ('option_type', models.CharField(max_length=2400)),
                ('option_attrs', jsonfield.fields.JSONField()),
                ('ta_topic_id', models.CharField(max_length=8)),
                ('topic_id', models.CharField(max_length=8)),
                ('client_id', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EngagementOpportunityLookupByProvider',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('external_id', models.CharField(max_length=2400)),
                ('provider_type', models.CharField(max_length=2400)),
                ('prospect_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileLookupByProvider',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('external_id', models.CharField(max_length=2400)),
                ('provider_type', models.CharField(max_length=2400)),
                ('prospect_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='profilelookupbyprovider',
            unique_together=set([('external_id', 'provider_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='engagementopportunitylookupbyprovider',
            unique_together=set([('external_id', 'provider_type')]),
        ),
    ]
