# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('relational', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EOLookupForEA',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('eo_attrs', jsonfield.fields.JSONField()),
                ('profile_id', models.CharField(max_length=8)),
                ('prospect_id', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileLookupForEA',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('profile_attrs', jsonfield.fields.JSONField()),
                ('prospect_id', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProspectLookupForEA',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('attrs', jsonfield.fields.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
