# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTATopicOption',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('option_name', models.CharField(max_length=2400)),
                ('option_type', models.CharField(max_length=2400)),
                ('option_attrs', jsonfield.fields.JSONField()),
                ('ta_topic_id', models.CharField(max_length=8)),
                ('topic_id', models.CharField(max_length=8)),
                ('client_id', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
