# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLookupByProvider',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=8, unique=True)),
                ('external_id', models.CharField(max_length=2400)),
                ('provider_type', models.CharField(max_length=2400)),
                ('prospect_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='profilelookupbyprovider',
            unique_together=set([('external_id', 'provider_type')]),
        ),
    ]
